// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DbUpdate.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace MessageShared {
  public static partial class mDbUpdateService
  {
    static readonly string __ServiceName = "MessageShared.mDbUpdateService";

    static readonly grpc::Marshaller<global::MessageShared.mDbUpdateRequest> __Marshaller_MessageShared_mDbUpdateRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MessageShared.mDbUpdateRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::MessageShared.mDbUpdateReply> __Marshaller_MessageShared_mDbUpdateReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MessageShared.mDbUpdateReply.Parser.ParseFrom);

    static readonly grpc::Method<global::MessageShared.mDbUpdateRequest, global::MessageShared.mDbUpdateReply> __Method_Send = new grpc::Method<global::MessageShared.mDbUpdateRequest, global::MessageShared.mDbUpdateReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Send",
        __Marshaller_MessageShared_mDbUpdateRequest,
        __Marshaller_MessageShared_mDbUpdateReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::MessageShared.DbUpdateReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of mDbUpdateService</summary>
    public abstract partial class mDbUpdateServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::MessageShared.mDbUpdateReply> Send(global::MessageShared.mDbUpdateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for mDbUpdateService</summary>
    public partial class mDbUpdateServiceClient : grpc::ClientBase<mDbUpdateServiceClient>
    {
      /// <summary>Creates a new client for mDbUpdateService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public mDbUpdateServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for mDbUpdateService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public mDbUpdateServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected mDbUpdateServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected mDbUpdateServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::MessageShared.mDbUpdateReply Send(global::MessageShared.mDbUpdateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Send(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::MessageShared.mDbUpdateReply Send(global::MessageShared.mDbUpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Send, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::MessageShared.mDbUpdateReply> SendAsync(global::MessageShared.mDbUpdateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::MessageShared.mDbUpdateReply> SendAsync(global::MessageShared.mDbUpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Send, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override mDbUpdateServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new mDbUpdateServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(mDbUpdateServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Send, serviceImpl.Send).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, mDbUpdateServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Send, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::MessageShared.mDbUpdateRequest, global::MessageShared.mDbUpdateReply>(serviceImpl.Send));
    }

  }
}
#endregion
