// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: log.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace MessageShared {
  public static partial class svcLogService
  {
    static readonly string __ServiceName = "MessageShared.svcLogService";

    static readonly grpc::Marshaller<global::MessageShared.mLOG> __Marshaller_MessageShared_mLOG = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MessageShared.mLOG.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::MessageShared.mLogResult> __Marshaller_MessageShared_mLogResult = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MessageShared.mLogResult.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::MessageShared.mLogText> __Marshaller_MessageShared_mLogText = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MessageShared.mLogText.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::MessageShared.mLogTextResult> __Marshaller_MessageShared_mLogTextResult = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MessageShared.mLogTextResult.Parser.ParseFrom);

    static readonly grpc::Method<global::MessageShared.mLOG, global::MessageShared.mLogResult> __Method_writeLog = new grpc::Method<global::MessageShared.mLOG, global::MessageShared.mLogResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "writeLog",
        __Marshaller_MessageShared_mLOG,
        __Marshaller_MessageShared_mLogResult);

    static readonly grpc::Method<global::MessageShared.mLogText, global::MessageShared.mLogTextResult> __Method_writeLogText = new grpc::Method<global::MessageShared.mLogText, global::MessageShared.mLogTextResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "writeLogText",
        __Marshaller_MessageShared_mLogText,
        __Marshaller_MessageShared_mLogTextResult);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::MessageShared.LogReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of svcLogService</summary>
    public abstract partial class svcLogServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::MessageShared.mLogResult> writeLog(global::MessageShared.mLOG request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::MessageShared.mLogTextResult> writeLogText(global::MessageShared.mLogText request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for svcLogService</summary>
    public partial class svcLogServiceClient : grpc::ClientBase<svcLogServiceClient>
    {
      /// <summary>Creates a new client for svcLogService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public svcLogServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for svcLogService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public svcLogServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected svcLogServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected svcLogServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::MessageShared.mLogResult writeLog(global::MessageShared.mLOG request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return writeLog(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::MessageShared.mLogResult writeLog(global::MessageShared.mLOG request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_writeLog, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::MessageShared.mLogResult> writeLogAsync(global::MessageShared.mLOG request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return writeLogAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::MessageShared.mLogResult> writeLogAsync(global::MessageShared.mLOG request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_writeLog, null, options, request);
      }
      public virtual global::MessageShared.mLogTextResult writeLogText(global::MessageShared.mLogText request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return writeLogText(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::MessageShared.mLogTextResult writeLogText(global::MessageShared.mLogText request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_writeLogText, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::MessageShared.mLogTextResult> writeLogTextAsync(global::MessageShared.mLogText request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return writeLogTextAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::MessageShared.mLogTextResult> writeLogTextAsync(global::MessageShared.mLogText request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_writeLogText, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override svcLogServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new svcLogServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(svcLogServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_writeLog, serviceImpl.writeLog)
          .AddMethod(__Method_writeLogText, serviceImpl.writeLogText).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, svcLogServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_writeLog, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::MessageShared.mLOG, global::MessageShared.mLogResult>(serviceImpl.writeLog));
      serviceBinder.AddMethod(__Method_writeLogText, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::MessageShared.mLogText, global::MessageShared.mLogTextResult>(serviceImpl.writeLogText));
    }

  }
}
#endregion
