// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CacheFind.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace MessageShared {
  public static partial class mCacheService
  {
    static readonly string __ServiceName = "MessageShared.mCacheService";

    static readonly grpc::Marshaller<global::MessageShared.mCacheRequest> __Marshaller_MessageShared_mCacheRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MessageShared.mCacheRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::MessageShared.mCacheReply> __Marshaller_MessageShared_mCacheReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MessageShared.mCacheReply.Parser.ParseFrom);

    static readonly grpc::Method<global::MessageShared.mCacheRequest, global::MessageShared.mCacheReply> __Method_Send = new grpc::Method<global::MessageShared.mCacheRequest, global::MessageShared.mCacheReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Send",
        __Marshaller_MessageShared_mCacheRequest,
        __Marshaller_MessageShared_mCacheReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::MessageShared.CacheFindReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of mCacheService</summary>
    public abstract partial class mCacheServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::MessageShared.mCacheReply> Send(global::MessageShared.mCacheRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for mCacheService</summary>
    public partial class mCacheServiceClient : grpc::ClientBase<mCacheServiceClient>
    {
      /// <summary>Creates a new client for mCacheService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public mCacheServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for mCacheService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public mCacheServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected mCacheServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected mCacheServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::MessageShared.mCacheReply Send(global::MessageShared.mCacheRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Send(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::MessageShared.mCacheReply Send(global::MessageShared.mCacheRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Send, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::MessageShared.mCacheReply> SendAsync(global::MessageShared.mCacheRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::MessageShared.mCacheReply> SendAsync(global::MessageShared.mCacheRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Send, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override mCacheServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new mCacheServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(mCacheServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Send, serviceImpl.Send).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, mCacheServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Send, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::MessageShared.mCacheRequest, global::MessageShared.mCacheReply>(serviceImpl.Send));
    }

  }
}
#endregion
