// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: message.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace F88.Message {
  public static partial class svcMessageService
  {
    static readonly string __ServiceName = "F88.Message.svcMessageService";

    static readonly grpc::Marshaller<global::F88.Message.mRequest> __Marshaller_F88_Message_mRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::F88.Message.mRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::F88.Message.mResponse> __Marshaller_F88_Message_mResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::F88.Message.mResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::F88.Message.mRequest, global::F88.Message.mResponse> __Method_sendMsg = new grpc::Method<global::F88.Message.mRequest, global::F88.Message.mResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "sendMsg",
        __Marshaller_F88_Message_mRequest,
        __Marshaller_F88_Message_mResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::F88.Message.MessageReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of svcMessageService</summary>
    public abstract partial class svcMessageServiceBase
    {
      public virtual global::System.Threading.Tasks.Task sendMsg(grpc::IAsyncStreamReader<global::F88.Message.mRequest> requestStream, grpc::IServerStreamWriter<global::F88.Message.mResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for svcMessageService</summary>
    public partial class svcMessageServiceClient : grpc::ClientBase<svcMessageServiceClient>
    {
      /// <summary>Creates a new client for svcMessageService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public svcMessageServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for svcMessageService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public svcMessageServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected svcMessageServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected svcMessageServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncDuplexStreamingCall<global::F88.Message.mRequest, global::F88.Message.mResponse> sendMsg(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return sendMsg(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::F88.Message.mRequest, global::F88.Message.mResponse> sendMsg(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_sendMsg, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override svcMessageServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new svcMessageServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(svcMessageServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_sendMsg, serviceImpl.sendMsg).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, svcMessageServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_sendMsg, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::F88.Message.mRequest, global::F88.Message.mResponse>(serviceImpl.sendMsg));
    }

  }
}
#endregion
